### ISSUE TITLE
Actions funcionam apenas se declaradas na raiz

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-web-core#159]
Quando estávamos implementando as actions, resolvemos vasculhar apenas a raiz de cada componente procurando por actions. Assumimos que não fazia muito sentido declarar actions dentro de outras propriedades.

Na apresentação para o TDC, o exemplo utilizado pelo mobile coloca actions em `colorSwitcher.colors[x].onPress`, onde `x` é uma posição do array `options`. É certo de que o payload utilizado como exemplo está longe do ideal, mas não é uma limitação muito ruim esperar que as actions sempre venham na raiz do componente?

Se as actions continuam valendo apenas na raiz, isso tem que ser acordado com todas as frentes e bem documentado.

**Comment by hectorcustodiozup** [comment]
Criei uma aplicação React com um botão customizado chamando actions em diversos níveis do objeto. Testei com o seguinte payload e as ações foram chamadas corretamente em qualquer um dos níveis.
![image](https://user-images.githubusercontent.com/50678762/90544030-eb59e780-e15c-11ea-89ed-f82ebfa98c35.png)
