### ISSUE TITLE
Nulls no json devem ser interpretados como se não existissem

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-web-core#175]
No JSON do Beagle tratamos null como um valor, como é o correto no javascript, pois `null !== undefined`. Mas todas as outras frentes interpretam null como um valor inexistente no JSON, portanto, precisamos apagar os nulls antes de processar o json, impedindo que eles sejam processados pelo Beagle.

Task: adicionar pré-processamento do json onde propriedades com valor null são removidas.

OBS: Se der tempo de lançar como patch, antes da v1.1, basta criar um middleware.

**Comment by carolinegoncalveszup** [comment]
Done in https://github.com/ZupIT/beagle-web-core/pull/179
