### ISSUE TITLE
Analisar os impactos de se alterar o target de esnext para ES5

### ISSUE THREAD

**Issue by pedronaveszup** [ZupIT/beagle-web-core#191]
Atualmente estamos especificando o target da nossa lib como `esnext` e com isto nossa lib deixa de funcionar no IE 11-

Precisamos analisar os impactos de alterar o target da nossa lib para `es5`

Esta é uma task de análise para futuras decisões sobre como lidaremos com suporte ao IE 11-
- Descrever quais foram os impactos encontrados com a alteração do target.

**Comment by Tiagoperes** [comment]
This has never been done. On the bright side, after this much time we never had a problem. I'm closing this. If we do find a problem, new issues must be opened.
