### ISSUE TITLE
Documentar componentes de loading e error

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-web-core#204]
Deve-se escrever a documentação para componentes de loading e error customizados.

No caso do componente de erro, deve-se exemplificar o retry.

**Comment by hectorcustodiozup** [comment]
Adicionei um draft na doc para ser revisado, se estiver tudo certo eu faço o merge 
https://app.gitbook.com/@zup-products/s/beagle/~/drafts/-MHMnsusKlTRGfVMM1i1/v/v1.0-pt/features/customizacao/beagle-para-web/componentes-error-e-loading
