### ISSUE TITLE
Update web custom component example in the docs

### ISSUE THREAD

**Issue by carolinegoncalveszup** [ZupIT/beagle-web-core#218]
**What would you like to be added**:
The custom component that is presented in the docs for android and iOS is the same, the `ColorSelector` (see https://docs.usebeagle.io/features/componentes/criando-seu-componente/android). The web example is a completely different one, a `CustomText` (https://docs.usebeagle.io/features/componentes/criando-seu-componente/web). The idea is to have all the examples the same, showing how it would be implemented for each platform.

**Why is this needed**:
To keep the doc consistent between the different platforms

**Comment by Tiagoperes** [comment]
Transferred to the [docs repository](https://github.com/ZupIT/beagle-docs/issues/484).
