### ISSUE TITLE
Pre-fetch doesn't always work

### ISSUE THREAD

**Issue by Tiagoperes** [ZupIT/beagle-web-core#232]
Beagle Web version: 1.1.3

## Steps To Reproduce

1. Try to create a navigation action with pre-fetch in the following scenarios:
- Action declared as an array of actions instead of a single object (according to the docs). Example: `"onPress": [{ "_beagleAction_": "beagle:pushView", "route": { "url": "/test", "shouldPrefetch": true } }]`
- Action with all lowercase letters. Example "beagle:pushview".
- Action in any property that is not in the component's root. Example: `buttonGroup.first.onPress`.
- Action inside another action (nested actions). Example: `sendRequest.onSucess`.

2. Any of the scenarios above will not trigger the pre-fetch, i.e. the pre-fetch only works when the action is an object, is in the root of the component and has the exactly same casing as the original action.

## The current behavior
The pre-fetch doesn't work.

## The expected behavior
The pre-fetch should work.

Epic - https://github.com/ZupIT/beagle/issues/860

**Comment by pedronaveszup** [comment]
reminder: throw error message when prefetch are used in dynamic routes
