### ISSUE TITLE
Allow custom routing

### ISSUE THREAD

**Issue by carolinegoncalveszup** [ZupIT/beagle-web-core#250]
**What would you like to be added**:
It would be interesting if we were able to set a custom routing  function in the beagle config so instead of using window.location.href for the action `beagle:openNativeRoute` this custom would be used.

**Why is this needed**:
This is helpeful in at least two situations:
- Doing the navigation between different application router can be done using beagle:openNativeRoute so the route being opened can be or not another beagle view, this doesn't matter. The problem is that the way we are doing today reloads the entire screen. If the customization were possible, this problem could be solved passing angular router, for example when using beagle angular.
- Using angular option `--base-href` with a custom path instead of changing `base href` causes the beagle:openNativeRoute to doesn't work as expected. This is due the fact that angular router has the custom path as the basePath, but considering the way we handle the routing, the basePath doesn't have the custom part.

**Comment by Tiagoperes** [comment]
This is achievable by overwriting the action via configuration. Example:

```typescript
createBeagle
Service({
  // ...
  customActions: {
    'beagle:openNativeRoute': myCustomHandler,
  }
})
```
