### ISSUE TITLE
[Navegação] Possibilitar uso do Browser History no Beagle Navigator

### ISSUE THREAD

**Issue by raphaelspimenta** [ZupIT/beagle-web-core#58]
Criar possibilidade do desenvolvedor optar em utilizar o Browser History em sua navegação pelo Beagle. 

**What would you like to be added**:
Criar um novo parâmetro na configuração de uma view que determina o tipo de navegação da mesma. Esse poderá ser `BROWSER_HISTORY` ou `BEAGLE_NAVIGATOR` (default).

**Why is this needed**:
Atualmente o Beagle Navigator não interfere no history do browser, apenas altera o fluxo de paths dentro de uma view. Essa [issue](https://github.com/ZupIT/beagle/issues/53) aberta explica este fluxo. 
A ideia é disponibilizar a opção em que o Beagle Navigator também altera o history do browser. Nessa opção, ao executar uma ação de navegação, o beagle deve alterar a url adicionando uma **query string** com o path desejado.

Obs.: Essa é a primeira solução pensada não definitiva.

**Comment by Tiagoperes** [comment]
Implementar um novo atributo na estrutura NavigationController:

- `useBrowserHistory: boolean`

esse atributo, assim como o próprio `navigationController`, é opcional. O valor padrão para `useBrowserHistory` é `false`.

Quando `useBrowserHistory` é `false`, o Beagle deve se comportar exatamente como se comporta hoje.

Quando `useBrowserHistory` é `true`, a navegação do Beagle deve ser atrelada à navegação do browser, ou seja, quando o usuário usar os botões de "voltar" e "próximo" do browser, a view do beagle deve ser alterada de acordo.
